### ISSUE TITLE
build failed 

### ISSUE THREAD

**Issue by duanwujie** [geany/geany-osx#10]
we use the gtk3+  but failed at last step:

```
MacdeMacBook-Air:geany-osx mac$ jhbuild shell
Loading .env environment variables…
Prefix: /Users/mac/gtk/inst
Entered jhbuild shell, type 'exit' to return.
bash-3.2$  gtk-mac-bundler geany-gtk3.bundle
Traceback (most recent call last):
  File "/Users/mac/.new_local/bin/gtk-mac-bundler", line 6, in <module>
    bundler.main.main(sys.argv[1:])
  File "/Users/mac/gtk/source/gtk-mac-bundler/bundler/main.py", line 18, in main
    bundler.run()
  File "/Users/mac/gtk/source/gtk-mac-bundler/bundler/bundler.py", line 479, in run
    self.resolve_library_dependencies()
  File "/Users/mac/gtk/source/gtk-mac-bundler/bundler/bundler.py", line 354, in resolve_library_dependencies
    source = path.compute_source_path(self.project)
  File "/Users/mac/gtk/source/gtk-mac-bundler/bundler/project.py", line 186, in compute_source_path
    raise ValueError("Cannot find source to copy: " + source)
ValueError: Cannot find source to copy: /Users/mac/gtk/inst/lib/gio/modules/*.so
```

**Comment by techee** [comment]
Should be fixed now.
