### ISSUE TITLE
Cannot execute hg via GeanyVC

### ISSUE THREAD

**Issue by frlan** [geany/geany-osx#5]
Not sure whether this is a 100% issue of the MacOS build, but I have seen such strange behaviour only on El Capitan by now. (Geany 1.29-dmg)

When trying to use Mercurial from GeanyVC I'm getting a backtrace

```
$ pwd
/Applications/Geany.app/Contents/MacOS
$ ./geany                                                                                                                                           1
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:/Library/TeX/texbin:/Library/TeX/texbin
2017-02-03 09:31:39.632 geany-bin[40089:622171] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead. 

(geany-bin:40089): SpellCheck-WARNING **: Stored language ('en_US') could not be loaded.
Traceback (most recent call last):
  File "/usr/local/bin/hg", line 44, in <module>
    mercurial.util.setbinary(fp)
  File "/usr/local/Cellar/mercurial/4.0.2/lib/python2.7/site-packages/mercurial/demandimport.py", line 152, in __getattribute__
    self._load()
  File "/usr/local/Cellar/mercurial/4.0.2/lib/python2.7/site-packages/mercurial/demandimport.py", line 100, in _load
    mod = _hgextimport(_import, head, globals, locals, None, level)
  File "/usr/local/Cellar/mercurial/4.0.2/lib/python2.7/site-packages/mercurial/demandimport.py", line 53, in _hgextimport
    return importfunc(name, globals, *args, **kwargs)
  File "/usr/local/Cellar/mercurial/4.0.2/lib/python2.7/site-packages/mercurial/util.py", line 122, in <module>
    statfiles = getattr(osutil, 'statfiles', platform.statfiles)
  File "/usr/local/Cellar/mercurial/4.0.2/lib/python2.7/site-packages/mercurial/demandimport.py", line 152, in __getattribute__
    self._load()
  File "/usr/local/Cellar/mercurial/4.0.2/lib/python2.7/site-packages/mercurial/demandimport.py", line 100, in _load
    mod = _hgextimport(_import, head, globals, locals, None, level)
  File "/usr/local/Cellar/mercurial/4.0.2/lib/python2.7/site-packages/mercurial/demandimport.py", line 53, in _hgextimport
    return importfunc(name, globals, *args, **kwargs)
  File "/usr/local/Cellar/mercurial/4.0.2/lib/python2.7/site-packages/mercurial/__init__.py", line 120, in load_module
    mod = imp.load_module(name, *modinfo)
ImportError: dlopen(/usr/local/Cellar/mercurial/4.0.2/lib/python2.7/site-packages/mercurial/osutil.so, 2): Symbol not found: _clock_gettime
  Referenced from: /Applications/Geany.app/Contents/Resources/lib/liblzma.5.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/Geany.app/Contents/Resources/lib/liblzma.5.dylib

(geany-bin:40089): GeanyVC-CRITICAL **: vcdiff_file_activated: assertion 'vc' failed
```

Mercurial is installed via brew and is working from normal shell. As well as e.g. git — also installed via brew — is working.

**Comment by elextr** [comment]
Version of Geany Glib and GTK (sorry @frlan :)

I guess this is @techee provided Geany port?

**Comment by frlan** [comment]
Yes. It's the DMG provided by @techee  ;)  (It was too obviously as in "what else somebody wants to use" to me that I left it out)

**Comment by techee** [comment]
@frlan Just tried (on Sierra though) and it seems to be working fine here. Tried to activate the plugin, installed hg from homebrew and tested it on a file from Scintilla repository which uses hg (tried blame, diff, history which all worked fine).

However, did you notice this

http://lists.geany.org/pipermail/users/2016-December/010169.html

Have you tried the new installer? This problem sounds like it might be fixed by the new binary.

**Comment by frlan** [comment]
I totally missed the updated installer. Just updated and working.

**Comment by techee** [comment]
Great!
